/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.peruncs.pcml.webapp;

class MessageUtilsTest {
//    @Test void testGetMessage() {
//        assertEquals("Hello      World!", MessageUtils.getMessage());
//    }
}
